services:
  postgres:
    image: docker.io/library/postgres
    container_name: socialcampus-postgres
    environment:
      POSTGRES_DB: socialcampus_db
      POSTGRES_USER: socialcampus_user
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - socialcampus-net

  mailhog:
    image: docker.io/mailhog/mailhog
    container_name: socialcampus-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - socialcampus-net

  minio:
    image: docker.io/minio/minio
    container_name: socialcampus-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - socialcampus-net

networks:
  socialcampus-net:

volumes:
  postgres_data:
  minio_data: