services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: socialcampus-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd.
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - socialcampus-net

  minio:
    image: minio/minio
    container_name: socialcampus-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - socialcampus-net

networks:
  socialcampus-net:

volumes:
  mssql_data:
  minio_data:
