services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword123!"
    ports:
      - "1433:1433"
